/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CInterface */

#ifndef _Included_CInterface
#define _Included_CInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CInterface
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CInterface_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     CInterface
 * Method:    getBpm
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CInterface_getBpm
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
